apply plugin: 'com.github.johnrengelman.shadow'

dependencies {
    implementation project(':common')
    implementation libs.flink.sql.connector.mysql.cdc
    compileOnly libs.flink.streaming.java
    compileOnly libs.flink.clients
    compileOnly libs.flink.table.api.java.bridge
    compileOnly libs.flink.table.planner.loader
}

shadowJar {
    manifest { attributes 'Main-Class': 'poc.tableapi.TableApiCdcJob' }
    mergeServiceFiles()
}
